# Generated by Django 3.1.5 on 2023-09-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название фильма')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('time_create', models.DateField(auto_now_add=True)),
                ('is_publish', models.BooleanField(default=True)),
                ('actors', models.TextField(blank=True, verbose_name='В главных ролях')),
                ('create_date', models.DateField(verbose_name='Дата выхода')),
                ('poster', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Постер')),
                ('rate', models.TextField(max_length=1, verbose_name='Рейтинг Кинопоиска')),
                ('video', models.URLField(verbose_name='Ссылка на трейлер')),
            ],
            options={
                'verbose_name': 'Список фильмов',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
