# Generated by Django 3.1.5 on 2023-09-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20230915_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Тип')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тип',
            },
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='item_name',
            new_name='name',
        ),
    ]
