# Generated by Django 3.1.5 on 2023-09-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20230918_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, to='films.Genre', verbose_name='Жанры'),
        ),
    ]
