# Generated by Django 3.1.5 on 2023-09-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='films.movietype', verbose_name='Тип'),
        ),
    ]
